name: Build model, push model to github registry, and deploy application

on:
  push:
    branches: [ main ]
    paths:
      - src/app/*
      - Dockerfile
      - .github/workflows/main.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_REGISTRY }}

    - name: Build app and push to registry
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: ghcr.io/${{ github.repository_owner }}/flask-app:latest
        push: true           

  deploy:
    needs: build
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2

      - name: Pull image from GitHub Registry
        run: docker pull ghcr.io/${{ github.repository_owner }}/flask-app:latest

      - name: Remove previously run containers if any
        run: docker rm -f flask-app
        
      - name: Run the container on EC2 instance
        run: docker run --rm -p 8080:8080 --name flask-app ghcr.io/${{ github.repository_owner }}/flask-app:latest