name: Build model, push model to github registry, and deploy application

on:
  push:
    branches: [ main ]
    paths:
      - src/app/*
      - Dockerfile
      - .github/workflows/main.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_REGISTRY }}

    - name: Build app and push to registry
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: ghcr.io/${{ github.repository_owner }}/flask-app:latest
        push: true           

  deploy:
    needs: build
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Pull image from GitHub Registry
        run: docker pull ghcr.io/${{ github.repository_owner }}/flask-app:latest

      - name: Remove previously run containers if any
        run: docker rm -f flask-app
        
      - name: Run the container on EC2 instance
        run: docker run --rm -p 8080:8080 --name flask-app ghcr.io/${{ github.repository_owner }}/flask-app:latest